apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_FINTECHNAME
          valueFrom:
            configMapKeyRef:
              name: frontend-configmap
              key: NEXT_PUBLIC_FINTECHNAME
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: frontend-configmap
              key: NODE_ENV